runtime: php55
api_version: 1
threadsafe: true
version: v1

handlers:

- url: /
  static_files: proposal/main_static.html
  upload: proposal/main_static.html

- url: /
  static_dir: proposal

env_variables:
  MYSQL_DSN: mysql:unix_socket=/cloudsql/backend-256601:us-central1:database;dbname=testdata
  MYSQL_USER: duttaadri2014@gmail.com
  MYSQL_PASSWORD: D6qs1FPzuOdE6JFu  


  