runtime: php55
api_version: 1
threadsafe: true
default_expiration: "10s"

handlers:
- url: /
  script: main_static.php

- url: /main_static\.php
  script: main_static.php

- url: /candidates\.php
  script: candidates.php

- url: /threads\.php
  script: threads.php

- url: /voting_info\.php
  script: voting_info.php

- url: /login\.php
  script: login.php

- url: /aboutme\.php
  script: aboutme.php

- url: /candidate_profile\.php
  script: candidate_profile.php

- url: /expanded_article_1\.php
  script: expanded_article_1.php

- url: /username\.php
  script: username.php

- url: /config\.php
  script: config.php

- url: /bookmark_keeping\.php
  script: bookmark_keeping.php

- url: /connection\.php
  script: connection.php

- url: /trump_profile\.php
  script: trump_profile.php

- url: /user_profile\.php
  script: user_profile.php

- url: /preference_send\.php
  script: preference_send.php

- url: /send_data_form\.php
  script: send_data_form.php

- url: /user_preference_factory\.php
  script: user_preference_factory.php

- url: /user_preference_main_factory\.php
  script: user_preference_main_factory.php  
- url: /
  static_dir: static_files

env_variables:
  MYSQL_DSN: mysql:unix_socket=/cloudsql/backend-256601:us-central1:database;dbname=testdata
  MYSQL_USER: duttaadri2014@gmail.com
  MYSQL_PASSWORD: D6qs1FPzuOdE6JFu  


  