runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: proposal/aboutme_js.js
  upload: proposal/aboutme_js.js

- url: /
  static_files: proposal/main_static.html
  upload: proposal/main_static.html

- url: /
  static_dir: proposal


  