// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void nextandPreviousbuttons() {
    driver.get("https://electionessentials.appspot.com");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("gun_violence")).click();
    driver.findElement(By.id("lgbtq")).click();
    driver.findElement(By.id("education")).click();
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.id("next-page")).click();
    driver.findElement(By.id("next-page")).click();
    driver.findElement(By.id("next-page")).click();
    driver.findElement(By.id("next-page")).click();
    driver.findElement(By.id("prev-page")).click();
    driver.findElement(By.id("prev-page")).click();
    driver.findElement(By.id("prev-page")).click();
    driver.findElement(By.id("prev-page")).click();
  }
  @Test
  public void bookmarking() {
    driver.get("https://electionessentials.appspot.com");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("environment")).click();
    driver.findElement(By.id("immigration")).click();
    driver.findElement(By.id("education")).click();
    driver.findElement(By.id("gun_violence")).click();
    driver.findElement(By.id("lgbtq")).click();
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.linkText("These Rats Drive Tiny Cars—for Science")).click();
    driver.findElement(By.linkText("ADD BOOKMARK")).click();
    driver.findElement(By.linkText("MY PROFILE")).click();
    driver.findElement(By.linkText("These Rats Drive Tiny Cars—for Science")).click();
    driver.findElement(By.linkText("REMOVE BOOKMARK")).click();
    driver.findElement(By.linkText("MY PROFILE")).click();
    driver.findElement(By.linkText("HOME")).click();
    driver.findElement(By.linkText("TikTok’s new set of safety videos teach users about features, the app’s focus on ‘positivity’")).click();
    driver.findElement(By.linkText("ADD BOOKMARK")).click();
    driver.findElement(By.linkText("MY PROFILE")).click();
    driver.findElement(By.linkText("TikTok’s new set of safety videos teach users about features, the app’s focus on ‘positivity’")).click();
    driver.findElement(By.linkText("MY PROFILE")).click();
    driver.findElement(By.cssSelector(".removeButton")).click();
    driver.findElement(By.linkText("HOME")).click();
    driver.findElement(By.linkText("TikTok’s new set of safety videos teach users about features, the app’s focus on ‘positivity’")).click();
    driver.findElement(By.linkText("ADD BOOKMARK")).click();
    driver.findElement(By.linkText("REMOVE BOOKMARK")).click();
  }
  @Test
  public void candidateCampaignLinks() {
    driver.get("https://electionessentials.appspot.com/candidates.php");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("Michael Bennet")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win6766", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win6766").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Joe\\ Biden img")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win2131", waitForWindow(2000));
    driver.switchTo().window(vars.get("win2131").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Cory\\ Booker img")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win6334", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6334").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Steve\\ Bullock img")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win1477", waitForWindow(2000));
    driver.switchTo().window(vars.get("win1477").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Pete\\ Buttigieg img")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win2516", waitForWindow(2000));
    driver.switchTo().window(vars.get("win2516").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Julian\\ Castro > .candidate-name")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win3067", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3067").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#John\\ Delaney img")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win1266", waitForWindow(2000));
    driver.switchTo().window(vars.get("win1266").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Tulsi\\ Gabbard img")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win4565", waitForWindow(2000));
    driver.switchTo().window(vars.get("win4565").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Kamala\\ Harris img")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win9354", waitForWindow(2000));
    driver.switchTo().window(vars.get("win9354").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Amy\\ Klobuchar img")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win9330", waitForWindow(2000));
    driver.switchTo().window(vars.get("win9330").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Wayne\\ Messam img")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win6594", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6594").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Bernie\\ Sanders img")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win2217", waitForWindow(2000));
    driver.switchTo().window(vars.get("win2217").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Joe\\ Sestak img")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win6882", waitForWindow(2000));
    driver.switchTo().window(vars.get("win6882").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.id("Tom Steyer")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win8666", waitForWindow(2000));
    driver.switchTo().window(vars.get("win8666").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Elizabeth\\ Warren img")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win1982", waitForWindow(2000));
    driver.switchTo().window(vars.get("win1982").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.id("Marianne Williamson")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win2343", waitForWindow(2000));
    driver.switchTo().window(vars.get("win2343").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.id("Andrew Yang")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win4500", waitForWindow(2000));
    driver.switchTo().window(vars.get("win4500").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.id("Donald Trump")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win879", waitForWindow(2000));
    driver.switchTo().window(vars.get("win879").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Joe\\ Walsh img")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win3674", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3674").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Bill\\ Weld img")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("here")).click();
    vars.put("win1643", waitForWindow(2000));
    driver.switchTo().window(vars.get("win1643").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
  }
  @Test
  public void candidates() {
    driver.get("https://electionessentials.appspot.com");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Michael\\ Bennet > .candidate-name")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Joe\\ Biden img")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Cory\\ Booker img")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Steve\\ Bullock img")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.id("Pete Buttigieg")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Julian\\ Castro img")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#John\\ Delaney img")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Tulsi\\ Gabbard img")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Kamala\\ Harris img")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Amy\\ Klobuchar img")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Wayne\\ Messam img")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Bernie\\ Sanders img")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Joe\\ Sestak img")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Tom\\ Steyer img")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Elizabeth\\ Warren img")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Marianne\\ Williamson img")).click();
    driver.findElement(By.id("candidateName")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Andrew\\ Yang img")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Donald\\ Trump img")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Joe\\ Walsh img")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
    driver.findElement(By.cssSelector("#Bill\\ Weld img")).click();
    driver.findElement(By.linkText("CANDIDATES")).click();
  }
  @Test
  public void savedessentialsloggedin() {
    driver.get("https://electionessentials.appspot.com");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("lgbtq")).click();
    driver.findElement(By.id("gun_violence")).click();
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.linkText("MY PROFILE")).click();
    driver.findElement(By.id("gun_violence")).click();
    driver.findElement(By.id("lgbtq")).click();
    driver.findElement(By.id("education")).click();
    driver.findElement(By.id("immigration")).click();
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.linkText("HOME")).click();
    driver.findElement(By.linkText("MY PROFILE")).click();
    driver.findElement(By.id("education")).click();
    driver.findElement(By.id("immigration")).click();
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.linkText("HOME")).click();
  }
  @Test
  public void twitterSharealreadyloggedin() {
    driver.get("https://electionessentials.appspot.com");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.id("jobs")).click();
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.linkText("Jobs Are Plentiful. Big Pay Raises Aren’t.")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".fa")).click();
    vars.put("win4057", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win4057").toString());
    driver.findElement(By.cssSelector(".button")).click();
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    {
      WebElement element = driver.findElement(By.linkText("VOTER INFORMATION"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
